--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Leon/Pictures/Wallpapers/pineforest.jpg"

-- Special
background="#0c0a1f"
foreground="#a3a1c9"
cursor="#a3a1c9"

-- Colors
color0="#0c0a1f"
color1="#CA7063"
color2="#233B99"
color3="#38439A"
color4="#1645AE"
color5="#344FB1"
color6="#464EA2"
color7="#a3a1c9"
color8="#72708c"
color9="#CA7063"
color10="#233B99"
color11="#38439A"
color12="#1645AE"
color13="#344FB1"
color14="#464EA2"
color15="#a3a1c9"
