# Shell variables
# Generated by 'wal'
wallpaper='/home/Leon/Pictures/Wallpapers/pineforest.jpg'

# Special
background='#0c0a1f'
foreground='#a3a1c9'
cursor='#a3a1c9'

# Colors
color0='#0c0a1f'
color1='#CA7063'
color2='#233B99'
color3='#38439A'
color4='#1645AE'
color5='#344FB1'
color6='#464EA2'
color7='#a3a1c9'
color8='#72708c'
color9='#CA7063'
color10='#233B99'
color11='#38439A'
color12='#1645AE'
color13='#344FB1'
color14='#464EA2'
color15='#a3a1c9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
